# The URL the site will be built for
base_url = "https://plamper.org"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "en"

author = "Felix Plamper"

generate_sitemap = true
generate_robots_txt = true

generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]

[markdown.highlighting]
theme = "kanagawa-dragon"

[extra]
# Put all your custom variables here
